.TH BACKCTL 1 backctl\-1.0
.SH NAME
backctl \- an xbacklight replacement
.SH SYNOPSIS
.B backctl
.RB [ \-inc ]
.RB [ \-dec ]
.RB [ \-set ]
.RB [ \-get ]
.RB [ \-get-perc ]
.RB [ \-help ]
.RB [ \-version ]

.B backctl
.RB [ + ]
.RB [ \- ]
.RB [ \-s ]
.RB [ \-g ]
.RB [ \-gp ]
.RB [ \-h ]
.RB [ \-v ]
.SH DESCRIPTION
.B backctl
is a sensible backlight control program, that aims to have compatibility with the 
.B xbacklight
tool. This tool was created out of frustration with xbacklight not supporting the
AMD Backlight devices
.SH OPTIONS
.SH AUTHORS
.B Rebecca White
<rtw@null.net>
.SH LICENSE
Copyright (C) 2024	Rebecca White <rtw@null.net>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
